import * as React from 'react';
import styles from '../styles/Home.module.css'
import { useGetPlayers } from '../components/useRequest';
import TeamGrid from '../components/MainBox/TeamGrid';
import NavBar from '../components/NavBar/NavBar';
import PlayerSelecter from '../components/PlayerSelecter/PlayerSelecter';
import { ThemeProvider } from '@mui/material/styles';
import { Box, Grid } from '@mui/material';
import theme from '../Theme';

import { store } from '../redux/store'
import { Provider } from 'react-redux'

const team = null

export default function Home() {

  const { data: allPlayers, error } = useGetPlayers(); // fetching all players from api 

  return (
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <NavBar/>
        <Grid container justifyContent='center'>
          <Box  
            sx={{ bgcolor: 'background', boxShadow: 1, borderRadius: 2, p: 2, minWidth: 300, maxWidth: 1000,  marginTop: 3, marginLeft: 2, marginRight: 2, width: 'auto' }}>
            <TeamGrid team={team}/>
          </Box>
          <PlayerSelecter allPlayers={allPlayers} />
        </Grid>
      </ThemeProvider>
    </Provider>
  );
}

/*
function Player({ player }) {
  const { web_name, now_cost, total_points } = player;
  return (
    <>
      <div className="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg">
        <p className="font-medium">
          {web_name}. {total_points}
        </p>
        <p>{now_cost}</p>
      </div>
    </>
  );
}

function Home() {

  const { data: players, error } = useGetPlayers();
  if (!players) return <h1>Loading...</h1>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        {players.map((player) => (
          <Player player={player} key={player.id} />
        ))}
        
      </main>
    </div>
  )
}
*/

